Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../organizations/ordererOrganizations/example.com/msp
        Policies:
        ....
        OrdererEndpoints:
            - orderer.example.com:7050
    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: ../organizations/peerOrganizations/org1.example.com/msp
        Policies:
            ...
        AnchorPeers:
        - Host: peer0.org1.example.com
        Port: 7051
    - &Org2
        AnchorPeers:
        - Host: peer0.org2.example.com
          Port: 9051
    - &Org3
        AnchorPeers:
        - Host: peer0.org3.example.com
          Port: 11051
Policies:
    Readers:
        Type: Signature
        Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
    Endorsement:
        Type: Signature
        Rule: "OR('Org2MSP.peer')"
Profiles:
    SupplyChainLedgerOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SupplyChainLedgerConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
    SupplyChainLedgerChannel:
        Consortium: SupplyChainLedgerConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
            Capabilities:
                <<: *ApplicationCapabilities